### ISSUE TITLE
SDL_Init triggers core dump on OS2.0.0.7111 with NDK Beta3

### ISSUE THREAD

**Issue by trevornunes** [blackberry/SDL#10]
OS 2.0.0.7111  0x4ddb148 _malloc_error_internal 

I'm running into a strange crash compiling 'DGEN' a Sega Genesis emulator. The 1.0 package works fine but the same code  appears to trigger a core file. It's dead after a call to SDL_Init.  No idea how to pursue this further since it's corrupting in a runtime library ...

https://github.com/trevornunes/DGEN/blob/master/src/sdl/sdl.cpp#L1229    It dies not long after this call ...

Backtrace and dissassembly follow:

Thread [1](Suspended : Signal : SIGABRT:Aborted)  
    SignalKill() at 0x4dec4f0  
    raise() at 0x4ddc9e4  
    0x4ddb148  
    0x4ddb148    

```
      _malloc_error_internal:
```

04ddb0a0:   ldr r12, [pc, #56]      ; 0x4ddb0e0 <_malloc_error_internal+64>
04ddb0a4:   mov r3, r2
04ddb0a8:   push {r4, lr}
04ddb0ac:   mov r4, r0
04ddb0b0:   ldr r0, [pc, #44]       ; 0x4ddb0e4 <_malloc_error_internal+68>
04ddb0b4:   mov lr, r1
04ddb0b8:   add r12, pc, r12
04ddb0bc:   mov r2, lr
04ddb0c0:   add r0, r12, r0
04ddb0c4:   mov r1, r4
04ddb0c8:   bl 0x4dc4694
04ddb0cc:   mvn r3, #0
04ddb0d0:   mov r2, #0
04ddb0d4:   mov r0, #1
04ddb0d8:   str r2, [r3]
04ddb0dc:   bl 0x4dc6794
04ddb0e0:   andeq r1, r5, r0, asr #30
04ddb0e4:    ; <UNDEFINED> instruction: 0xffffa80c
04ddb0e8:   push {r4, r5, r6, lr}
04ddb0ec:   sub sp, sp, #24
04ddb0f0:   mov r0, #6
04ddb0f4:   mov r1, #0
04ddb0f8:   mov r2, sp
04ddb0fc:   bl 0x4dc5aa4
04ddb100:   ldr r0, [sp]
04ddb104:   cmp r0, #1
04ddb108:   beq 0x4ddb184
04ddb10c:   cmp r0, #0
04ddb110:   beq 0x4ddb1a4
04ddb114:   add r4, sp, #16
04ddb118:   mov r5, #0
04ddb11c:   mov r0, r4
04ddb120:   bl 0x4dc59b4
04ddb124:   mov r1, #6
04ddb128:   mov r0, r4
04ddb12c:   bl 0x4dc6638
04ddb130:   mov r1, r4
04ddb134:   mov r2, r5
04ddb138:   mov r0, #2
04ddb13c:   bl 0x4dc58c4
04ddb140:   mov r0, #6
04ddb144:   bl 0x4dc6b3c
04ddb148:   mov r0, r5        <<<<<<<<<<<<   ABRT
04ddb14c:   bl 0x4dc4f40
04ddb150:   mov r1, sp
04ddb154:   mov r2, r5
04ddb158:   mov r0, #6
04ddb15c:   str r5, [sp]
04ddb160:   bl 0x4dc5aa4

**Comment by jnicholl** [comment]
Any chance you could send us playbookrom.h? We can't build it to check it out at the moment.
Also, the projects don't seem to be configured to build in debug mode.

----- Original Message -----
From: Trevor Nunes [mailto:reply@reply.github.com]
Sent: Tuesday, February 07, 2012 12:51 AM
To: Jeremy Nicholl
Subject: [SDL] SDL_Init triggers core dump on OS2.0.0.7111 with NDK Beta3 (#10)

OS 2.0.0.7111  0x4ddb148 _malloc_error_internal 

I'm running into a strange crash compiling 'DGEN' a Sega Genesis emulator. The 1.0 package works fine but the same code  appears to trigger a core file. It's dead after a call to SDL_Init.  No idea how to pursue this further since it's corrupting in a runtime library ...

https://github.com/trevornunes/DGEN/blob/master/src/sdl/sdl.cpp#L1229    It dies not long after this call ...

Backtrace and dissassembly follow:

Thread [1](Suspended : Signal : SIGABRT:Aborted)  
    SignalKill() at 0x4dec4f0  
    raise() at 0x4ddc9e4  
    0x4ddb148  
    0x4ddb148    

```
      _malloc_error_internal:
```

04ddb0a0:   ldr r12, [pc, #56]      ; 0x4ddb0e0 <_malloc_error_internal+64>
04ddb0a4:   mov r3, r2
04ddb0a8:   push {r4, lr}
04ddb0ac:   mov r4, r0
04ddb0b0:   ldr r0, [pc, #44]       ; 0x4ddb0e4 <_malloc_error_internal+68>
04ddb0b4:   mov lr, r1
04ddb0b8:   add r12, pc, r12
04ddb0bc:   mov r2, lr
04ddb0c0:   add r0, r12, r0
04ddb0c4:   mov r1, r4
04ddb0c8:   bl 0x4dc4694
04ddb0cc:   mvn r3, #0
04ddb0d0:   mov r2, #0
04ddb0d4:   mov r0, #1
04ddb0d8:   str r2, [r3]
04ddb0dc:   bl 0x4dc6794
04ddb0e0:   andeq r1, r5, r0, asr #30
04ddb0e4:    ; <UNDEFINED> instruction: 0xffffa80c
04ddb0e8:   push {r4, r5, r6, lr}
04ddb0ec:   sub sp, sp, #24
04ddb0f0:   mov r0, #6
04ddb0f4:   mov r1, #0
04ddb0f8:   mov r2, sp
04ddb0fc:   bl 0x4dc5aa4
04ddb100:   ldr r0, [sp]
04ddb104:   cmp r0, #1
04ddb108:   beq 0x4ddb184
04ddb10c:   cmp r0, #0
04ddb110:   beq 0x4ddb1a4
04ddb114:   add r4, sp, #16
04ddb118:   mov r5, #0
04ddb11c:   mov r0, r4
04ddb120:   bl 0x4dc59b4
04ddb124:   mov r1, #6
04ddb128:   mov r0, r4
04ddb12c:   bl 0x4dc6638
04ddb130:   mov r1, r4
04ddb134:   mov r2, r5
04ddb138:   mov r0, #2
04ddb13c:   bl 0x4dc58c4
04ddb140:   mov r0, #6
04ddb144:   bl 0x4dc6b3c
04ddb148:   mov r0, r5        <<<<<<<<<<<<   ABRT
04ddb14c:   bl 0x4dc4f40
04ddb150:   mov r1, sp
04ddb154:   mov r2, r5
04ddb158:   mov r0, #6
04ddb15c:   str r5, [sp]
04ddb160:   bl 0x4dc5aa4

---

Reply to this email directly or view it on GitHub:
https://github.com/blackberry/SDL/issues/10

---

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by trevornunes** [comment]
Yeah sorry the libpbrom is on my github but I didn't push the latest so romCount method is missing.  I need to cleanup all the projects , I will try and get this done soon but work is busy.

http://tbotz.blogspot.com

-----Original Message-----
From: Jeremy Nicholl reply@reply.github.com
Date: Tue, 7 Feb 2012 05:56:43 
To: Trevor Nunestrevor.nunes@gmail.com
Subject: Re: [SDL] SDL_Init triggers core dump on OS2.0.0.7111 with NDK Beta3 (#10)

Any chance you could send us playbookrom.h? We can't build it to check it out at the moment.
Also, the projects don't seem to be configured to build in debug mode.

----- Original Message -----
From: Trevor Nunes [mailto:reply@reply.github.com]
Sent: Tuesday, February 07, 2012 12:51 AM
To: Jeremy Nicholl
Subject: [SDL] SDL_Init triggers core dump on OS2.0.0.7111 with NDK Beta3 (#10)

OS 2.0.0.7111  0x4ddb148 _malloc_error_internal 

I'm running into a strange crash compiling 'DGEN' a Sega Genesis emulator. The 1.0 package works fine but the same code  appears to trigger a core file. It's dead after a call to SDL_Init.  No idea how to pursue this further since it's corrupting in a runtime library ...

https://github.com/trevornunes/DGEN/blob/master/src/sdl/sdl.cpp#L1229    It dies not long after this call ...

Backtrace and dissassembly follow:

Thread [1](Suspended : Signal : SIGABRT:Aborted)  
    SignalKill() at 0x4dec4f0  
    raise() at 0x4ddc9e4  
    0x4ddb148  
    0x4ddb148    

```
      _malloc_error_internal:
```

04ddb0a0:   ldr r12, [pc, #56]      ; 0x4ddb0e0 <_malloc_error_internal+64>
04ddb0a4:   mov r3, r2
04ddb0a8:   push {r4, lr}
04ddb0ac:   mov r4, r0
04ddb0b0:   ldr r0, [pc, #44]       ; 0x4ddb0e4 <_malloc_error_internal+68>
04ddb0b4:   mov lr, r1
04ddb0b8:   add r12, pc, r12
04ddb0bc:   mov r2, lr
04ddb0c0:   add r0, r12, r0
04ddb0c4:   mov r1, r4
04ddb0c8:   bl 0x4dc4694
04ddb0cc:   mvn r3, #0
04ddb0d0:   mov r2, #0
04ddb0d4:   mov r0, #1
04ddb0d8:   str r2, [r3]
04ddb0dc:   bl 0x4dc6794
04ddb0e0:   andeq r1, r5, r0, asr #30
04ddb0e4:    ; <UNDEFINED> instruction: 0xffffa80c
04ddb0e8:   push {r4, r5, r6, lr}
04ddb0ec:   sub sp, sp, #24
04ddb0f0:   mov r0, #6
04ddb0f4:   mov r1, #0
04ddb0f8:   mov r2, sp
04ddb0fc:   bl 0x4dc5aa4
04ddb100:   ldr r0, [sp]
04ddb104:   cmp r0, #1
04ddb108:   beq 0x4ddb184
04ddb10c:   cmp r0, #0
04ddb110:   beq 0x4ddb1a4
04ddb114:   add r4, sp, #16
04ddb118:   mov r5, #0
04ddb11c:   mov r0, r4
04ddb120:   bl 0x4dc59b4
04ddb124:   mov r1, #6
04ddb128:   mov r0, r4
04ddb12c:   bl 0x4dc6638
04ddb130:   mov r1, r4
04ddb134:   mov r2, r5
04ddb138:   mov r0, #2
04ddb13c:   bl 0x4dc58c4
04ddb140:   mov r0, #6
04ddb144:   bl 0x4dc6b3c
04ddb148:   mov r0, r5        <<<<<<<<<<<<   ABRT
04ddb14c:   bl 0x4dc4f40
04ddb150:   mov r1, sp
04ddb154:   mov r2, r5
04ddb158:   mov r0, #6
04ddb15c:   str r5, [sp]
04ddb160:   bl 0x4dc5aa4

---

Reply to this email directly or view it on GitHub:
https://github.com/blackberry/SDL/issues/10

---

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

---

**Comment by jnicholl** [comment]
No problem. We got it to build ... However, it seems to run without problems. Can you give any more details? Maybe build in debug mode?

----- Original Message -----

**Comment by trevornunes** [comment]
Haha,  I get the same error in debug and release .. Are you running the public beta and compiling with beta3 ndk ?

http://tbotz.blogspot.com

-----Original Message-----
From: Jeremy Nicholl reply@reply.github.com
Date: Tue, 7 Feb 2012 07:18:03 
To: Trevor Nunestrevor.nunes@gmail.com
Subject: Re: [SDL] SDL_Init triggers core dump on OS2.0.0.7111 with NDK Beta3 (#10)

No problem. We got it to build ... However, it seems to run without problems. Can you give any more details? Maybe build in debug mode?

----- Original Message -----

**Comment by jnicholl** [comment]
I'm not quite running the public beta build, but it's very close... I am using the same ndk.

----- Original Message -----

**Comment by trevornunes** [comment]
I secure wiped my playbook and re-installed a clean build of DGEN plus libs, get same core file.

**Comment by jnicholl** [comment]
Is the bar file you're trying hosted on your site? I could try it from there, perhaps?

----- Original Message -----

**Comment by trevornunes** [comment]
I ended up cloning the SDL git code using the git bash and blowing away the Momentics imported code ... This picks up the latest code and worked perfectly. I don't remember specifically selecting the wrong branch or older commit but for some reason files were missing in the SDL code and some other odd behaviours.  Anyway long story short I'm sticking with git-bash for importing until I can trust imports....
