### ISSUE TITLE
SDL_config.h vs SDL_platform.h inconsistency in defines

### ISSUE THREAD

**Issue by idispatch** [blackberry/SDL#3]
SDL_platforms.h defines the **QNXNTO**, but the provided SDL_config.h is not including the expected SDL_config_playbook.h, because the check is made against **PLAYBOOK** (which seems to be not defined) instead of **QNXNTO** (I suppose the check should be combined with something else, for simulator, for instance).

**Comment by idispatch** [comment]
In fact it routes to SDL_config_minimal.h

**Comment by jnicholl** [comment]
Did you import the project from github or build it with the Makefile system? The project defines **PLAYBOOK**

----- Original Message -----
From: Oleg [mailto:reply@reply.github.com]
Sent: Monday, December 12, 2011 02:48 AM
To: Jeremy Nicholl
Subject: [SDL] SDL_config.h vs SDL_platform.h inconsistency in defines (#3)

SDL_platforms.h defines the **QNXNTO**, but the provided SDL_config.h is not including the expected SDL_config_playbook.h, because the check is made against **PLAYBOOK** (which seems to be not defined) instead of **QNXNTO** (I suppose the check should be combined with something else, for simulator, for instance).

---

Reply to this email directly or view it on GitHub:
https://github.com/blackberry/SDL/issues/3

---

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by jnicholl** [comment]
This was a decision made early on in the port. Since the version of QNX that runs on Playbook does not support some of the API used in the existing QNX Neutrino port of SDL, I tried to separate the two via this define. It's a define of my own making, so it isn't defined by the compiler, but only in the NDK project settings.

I'd like to remove it at some point, but I don't know what the 'official' define is for future QNX devices to separate them from older ones.

Is this directly affecting your work? I had thought it should be fairly transparent.

-----Original Message-----
From: Oleg [mailto:reply@reply.github.com] 
Sent: Monday, December 12, 2011 2:49 AM
To: Jeremy Nicholl
Subject: [SDL] SDL_config.h vs SDL_platform.h inconsistency in defines (#3)

SDL_platforms.h defines the **QNXNTO**, but the provided SDL_config.h is not including the expected SDL_config_playbook.h, because the check is made against **PLAYBOOK** (which seems to be not defined) instead of **QNXNTO** (I suppose the check should be combined with something else, for simulator, for instance).

---

Reply to this email directly or view it on GitHub:
https://github.com/blackberry/SDL/issues/3

---

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by idispatch** [comment]
Indeed, I tried to make it using the makefile/unamanged build, so I got **PLAYBOOK** undefined. I started to create my own makefiles, so that explains the inconsistency. I believe the issues could be closed by now, Thank you!
